## Dataset

In [1]:
import numpy as np
import struct
import matplotlib.pyplot as plt
from tqdm import tqdm
import math
def load_mnist_images(filename):
    with open(filename, 'rb') as f:
        # Leggi intestazione: magic number, numero immagini, righe, colonne
        magic, num_images, rows, cols = struct.unpack(">IIII", f.read(16))
        # Leggi tutti i pixel e convertili in array numpy
        images = np.frombuffer(f.read(), dtype=np.uint8)
        # Ridimensiona l'array in (num_images, rows, cols)
        images = images.reshape((num_images, rows, cols))
    return images

def load_mnist_labels(filename):
    with open(filename, 'rb') as f:
        magic, num_labels = struct.unpack(">II", f.read(8))
        labels = np.frombuffer(f.read(), dtype=np.uint8)
    return labels
#-------------- Data Extraction ---------------------------

train_images = load_mnist_images('MNIST/train-images-idx3-ubyte')
train_labels = load_mnist_labels('MNIST/train-labels-idx1-ubyte')

test_images = load_mnist_images('MNIST/t10k-images.idx3-ubyte')
test_labels = load_mnist_labels('MNIST/t10k-labels.idx1-ubyte')

#--------------- Train data manipulation ------------------
print(train_images.shape)  # (60000, 28, 28)
print(train_labels.shape)  # (60000,)
one_hot_labels = np.zeros(train_labels.shape[0]*10).reshape((train_labels.shape[0]),10)
for i in range(len(train_labels)):
    one_hot_labels[i][train_labels[i]]=1
train_labels = one_hot_labels
print(train_labels.shape) # (60000,10)

#--------------- Test data manipulation -------------------
print(test_images.shape)  # (10000, 28, 28)
print(test_labels.shape)  # (10000,)
one_hot_labels = np.zeros(test_labels.shape[0]*10).reshape((test_labels.shape[0]),10)
for i in range(len(test_labels)):
    one_hot_labels[i][test_labels[i]]=1
test_labels = one_hot_labels
print(test_labels.shape) # (10000,10)

(60000, 28, 28)
(60000,)
(60000, 10)
(10000, 28, 28)
(10000,)
(10000, 10)


## CNN - PyTorch

The PyTorch model will be used as a reference to compute the weights since it's the fastest in training and the least prone to errors. If everything is written well, both slow and fast implementations of a CNN in numpy will give the same result, since the weights are the same.

### Model and Dataset Declaration with Training

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
import time
from tqdm import tqdm 

# 1.------------------ CNN declaration -------------------

class SimpleCNN(nn.Module):
    def __init__(self, num_classes=10):
        super(SimpleCNN, self).__init__()

        # --------- Convolutional Layers ------------
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=32, kernel_size=3, stride=2, padding=1)
        self.relu1 = nn.ReLU()

        self.conv2 = nn.Conv2d(in_channels=32, out_channels=64, kernel_size=3, stride=2, padding=1)
        self.relu2 = nn.ReLU()

        self.conv3 = nn.Conv2d(in_channels=64, out_channels=128, kernel_size=3, stride=2, padding=1)
        self.relu3 = nn.ReLU()
        # ---------- Flatten to become MLP's input -----------
        self.flatten = nn.Flatten()

        fc_input_size = 128 * 4 * 4
        # ---------- Multi Layer Perceptron ---------------
        # Only one hidden layer for classification
        self.fc1 = nn.Linear(in_features=fc_input_size, out_features=250)
        self.relu4 = nn.ReLU()
        self.fc2 = nn.Linear(in_features=250, out_features=num_classes)

    def forward(self, x):
        # First convolution
        x = self.conv1(x)
        x = self.relu1(x)

        # Second Convolution
        x = self.conv2(x)
        x = self.relu2(x)

        # Third Convolution
        x = self.conv3(x)
        x = self.relu3(x)

        # Flatten
        x = self.flatten(x)

        # MLP
        x = self.fc1(x)
        x = self.relu4(x)
        x = self.fc2(x)

        return x

# 2.------------------ CNN's Dataset declaration ----------------------

# class CNNDataset(Dataset):
#     def __init__(self, digits, labels, transform=None):
#         assert len(digits) == len(labels), "Number of digits and labels doesn't match"
#         self.digits = digits
#         self.labels = labels

#     def __len__(self):
#         return len(self.digits)

#     def __getitem__(self, idx):
#         digit = self.digits[idx]
#         label = self.labels[idx]
#         digit = digit.unsqueeze(0) # Needed operation to add the dimension of greyscale images (28,28) -> (1,28,28)
#         return digit, label

# tri = torch.from_numpy(train_images).float() / 255
# trl = torch.from_numpy(train_labels).float()
# tsi = torch.from_numpy(test_images).float() / 255
# tsl = torch.from_numpy(test_labels).float()

# train_dataset = CNNDataset(tri,trl)
# test_dataset = CNNDataset(tsi,tsl)

# batch_size = 128
# train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
# test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

# # 3.------ Training Setup ---------------

# device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# print(f"device: {device}")

# model = SimpleCNN(num_classes=10).to(device)

# # Loss definition
# criterion = nn.CrossEntropyLoss() 

# # Optimisation definition
# learning_rate = 0.001
# optimizer = optim.Adam(model.parameters(), lr=learning_rate)

# num_epochs = 5 

# # 4.------- cycle training ------

# print("\nStarting Training...")
# for epoch in range(num_epochs):

#     model.train() 

#     running_loss = 0.0
#     start_time = time.time()
#     #tqdm is module used to have a progress bar
#     progress_bar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{num_epochs}", leave=False)

#     for inputs, labels in progress_bar:

#         # move data on the device
#         inputs, labels = inputs.to(device), labels.to(device)

#         # make all gradients zero to avoid learning on gradients of previous steps
#         optimizer.zero_grad()

#         # Forward pass
#         outputs = model(inputs) 
#         # loss computation
#         loss = criterion(outputs, labels)

#         # Backward pass: compute the gradients
#         loss.backward()

#         # Weights update
#         optimizer.step()

#         # Update the loss
#         running_loss += loss.item() * inputs.size(0) # multiply for batch size to obtain the correct mean

#         # Update the progress bar
#         progress_bar.set_postfix(loss=f"{loss.item():.4f}")

#     # Epochs' mean loss computation
#     epoch_loss = running_loss / len(train_loader.dataset)
#     epoch_time = time.time() - start_time

#     print(f"Epoch {epoch+1}/{num_epochs} - Tempo: {epoch_time:.2f}s - Training Loss: {epoch_loss:.4f}")

#     # --- Test evaluation (after every epoch) ---
#     model.eval()
#     test_loss = 0.0
#     correct = 0
#     total = 0

#     with torch.no_grad(): # Disable gradient computation (we don't need gradients since we don't want to update the model in this phase)
#         i=0
#         for inputs, labels in test_loader:
#             if i >= 1:
#                 continue
#             inputs, labels = inputs.to(device), labels.to(device)
#             outputs = model(inputs)
#             loss = criterion(outputs, labels)
#             test_loss += loss.item() * inputs.size(0)
#             _, predicted = torch.max(outputs.data, 1) # Obtain index with the maximum probability (it is our result)
#             _,labels = torch.max(labels,1) # same for the test labels
#             total += labels.size(0)
#             correct += (predicted==labels).sum().item()
#             i+=1

#     avg_test_loss = test_loss / len(test_loader.dataset)
#     accuracy = 100 * correct / total
#     print(f"Epoch {epoch+1}/{num_epochs} - Test Loss: {avg_test_loss:.4f} - Test Accuracy: {accuracy:.2f}%")


# print("\nTraining Complete.")
# #2m 9.4 secondi per avere un'epoca con cuda
# # save the model
# torch.save(model.state_dict(), 'simple_cnn_mnist.pth')

### Weights extraction

In [3]:
model = SimpleCNN(num_classes=10)
model.load_state_dict(torch.load('simple_cnn_mnist.pth', map_location=torch.device('cpu'),weights_only=True)) # Carica su CPU

model.eval() # good practice is to set model in evaluation when you want to extract weights

# --- Parameters Extraction ⛏️ and Numpy Conversion ---

# Weights container
numpy_weights = {}

# Move model on cpu
model.to('cpu')

print("⛏️ Weights and Bias Extraction ⛏️\n")

# Layer Conv1
# PyTorch weight shape: (out_channels, in_channels, kernel_height, kernel_width)
# NumPy expected: (in_channels, out_channels, kernel_width, kernel_height) -> (1, 32, 3, 3)
pyt_k1_w = model.conv1.weight.data.detach().numpy()
# Transpose: (out, in, kH, kW) -> (in, out, kW, kH)
numpy_weights['k1'] = pyt_k1_w
print("----------------------------------------")
print(pyt_k1_w[0][:1])
print("----------------------------------------")
print(numpy_weights['k1'][0][:1])
# PyTorch bias shape: (out_channels,)
numpy_weights['b_conv1'] = model.conv1.bias.data.detach().numpy() # Shape (32,)
print(f"k1: PyTorch Shape={pyt_k1_w.shape}, NumPy Shape={numpy_weights['k1'].shape}")
print(f"b_conv1: NumPy Shape={numpy_weights['b_conv1'].shape}")

# Layer Conv2
# PyTorch weight shape: (64, 32, 3, 3)
# NumPy expected: (32, 64, 3, 3)
pyt_k2_w = model.conv2.weight.data.detach().numpy()
numpy_weights['k2'] = pyt_k2_w
numpy_weights['b_conv2'] = model.conv2.bias.data.detach().numpy() # Shape (64,)
print(f"k2: PyTorch Shape={pyt_k2_w.shape}, NumPy Shape={numpy_weights['k2'].shape}")
print(f"b_conv2: NumPy Shape={numpy_weights['b_conv2'].shape}")

# Layer Conv3
# PyTorch weight shape: (128, 64, 3, 3)
# NumPy expected: (64, 128, 3, 3)
pyt_k3_w = model.conv3.weight.data.detach().numpy()
numpy_weights['k3'] = pyt_k3_w
numpy_weights['b_conv3'] = model.conv3.bias.data.detach().numpy() # Shape (128,)
print(f"k3: PyTorch Shape={pyt_k3_w.shape}, NumPy Shape={numpy_weights['k3'].shape}")
print(f"b_conv3: NumPy Shape={numpy_weights['b_conv3'].shape}")

# Layer FC1
# PyTorch weight shape: (out_features, in_features) -> (250, 2048)
# NumPy expected (per input @ W): (in_features, out_features) -> (2048, 250)
pyt_w1 = model.fc1.weight.data.detach().numpy()
numpy_weights['w1'] = pyt_w1.T # Trasponi
# PyTorch bias shape: (out_features,) -> (250,)
# NumPy expected (per aggiunta diretta): (1, out_features) -> (1, 250)
pyt_b1 = model.fc1.bias.data.detach().numpy()
numpy_weights['b1'] = pyt_b1.reshape(1, -1) # Rendi (1, 250)
print(f"w1: PyTorch Shape={pyt_w1.shape}, NumPy Shape={numpy_weights['w1'].shape}")
print(f"b1: PyTorch Shape={pyt_b1.shape}, NumPy Shape={numpy_weights['b1'].shape}")

# Layer FC2
# PyTorch weight shape: (num_classes, 250) -> (10, 250)
# NumPy expected: (250, num_classes) -> (250, 10)
pyt_w2 = model.fc2.weight.data.detach().numpy()
numpy_weights['w2'] = pyt_w2.T # Trasponi
# PyTorch bias shape: (num_classes,) -> (10,)
# NumPy expected: (1, num_classes) -> (1, 10)
pyt_b2 = model.fc2.bias.data.detach().numpy()
numpy_weights['b2'] = pyt_b2.reshape(1, -1) # Rendi (1, 10)
print(f"w2: PyTorch Shape={pyt_w2.shape}, NumPy Shape={numpy_weights['w2'].shape}")
print(f"b2: PyTorch Shape={pyt_b2.shape}, NumPy Shape={numpy_weights['b2'].shape}")

print("\nExtraction complete. Numpy weights are in the dictionary 'numpy_weights'.")

# Access Example:
np_k1 = numpy_weights['k1']
np_b_conv1 = numpy_weights['b_conv1']
np_k2 = numpy_weights['k2']
np_b_conv2 = numpy_weights['b_conv2']
np_k3 = numpy_weights['k3']
np_b_conv3 = numpy_weights['b_conv3']
np_w1 = numpy_weights['w1']
np_b1 = numpy_weights['b1']
np_w2 = numpy_weights['w2']
np_b2 = numpy_weights['b2']



# [[[[-0.06239345  0.16331542  0.28573602]
#    [ 0.299534    0.48019555  0.25194943]
#    [-0.24432278  0.3191273  -0.06802213]]]


#  [[[ 0.10294101 -0.14240074  0.01178457]
#    [ 0.3072691  -0.06823204  0.30347323]
#    [-0.06327374  0.3396498   0.07433306]]]



#    [[[[-0.06239345  0.16331542  0.28573602]
#    [ 0.299534    0.48019555  0.25194943]
#    [-0.24432278  0.3191273  -0.06802213]]

#   [[ 0.10294101 -0.14240074  0.01178457]
#    [ 0.3072691  -0.06823204  0.30347323]
#    [-0.06327374  0.3396498   0.07433306]]

⛏️ Weights and Bias Extraction ⛏️

----------------------------------------
[[[-0.06239345  0.16331542  0.28573602]
  [ 0.299534    0.48019555  0.25194943]
  [-0.24432278  0.3191273  -0.06802213]]]
----------------------------------------
[[[-0.06239345  0.16331542  0.28573602]
  [ 0.299534    0.48019555  0.25194943]
  [-0.24432278  0.3191273  -0.06802213]]]
k1: PyTorch Shape=(32, 1, 3, 3), NumPy Shape=(32, 1, 3, 3)
b_conv1: NumPy Shape=(32,)
k2: PyTorch Shape=(64, 32, 3, 3), NumPy Shape=(64, 32, 3, 3)
b_conv2: NumPy Shape=(64,)
k3: PyTorch Shape=(128, 64, 3, 3), NumPy Shape=(128, 64, 3, 3)
b_conv3: NumPy Shape=(128,)
w1: PyTorch Shape=(250, 2048), NumPy Shape=(2048, 250)
b1: PyTorch Shape=(250,), NumPy Shape=(1, 250)
w2: PyTorch Shape=(10, 250), NumPy Shape=(250, 10)
b2: PyTorch Shape=(10,), NumPy Shape=(1, 10)

Extraction complete. Numpy weights are in the dictionary 'numpy_weights'.


## CNN - NumPy

### Padding

`np.pad()` takes as first argument the matrix to pad and as second argument a set of specification: for every dimension (in our case 4) it takes the number of paddings to add before and after the end of the dimension. If the objective is to pad only the image itself, which is found in the last two dimension, we should write:

`np.pad(img9,((0,0),(0,0),(pad,pad),(pad,pad)))` 

since dimensions are: BATCH, CHANNELS, HEIGHT, WIDTH

In [4]:
img9 = np.arange(1,37).reshape(2,2,3,3)
pad_img9 = np.pad(img9,((0,0),(0,0),(1,1),(1,1)))
print(img9)
print(pad_img9)

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]]

  [[10 11 12]
   [13 14 15]
   [16 17 18]]]


 [[[19 20 21]
   [22 23 24]
   [25 26 27]]

  [[28 29 30]
   [31 32 33]
   [34 35 36]]]]
[[[[ 0  0  0  0  0]
   [ 0  1  2  3  0]
   [ 0  4  5  6  0]
   [ 0  7  8  9  0]
   [ 0  0  0  0  0]]

  [[ 0  0  0  0  0]
   [ 0 10 11 12  0]
   [ 0 13 14 15  0]
   [ 0 16 17 18  0]
   [ 0  0  0  0  0]]]


 [[[ 0  0  0  0  0]
   [ 0 19 20 21  0]
   [ 0 22 23 24  0]
   [ 0 25 26 27  0]
   [ 0  0  0  0  0]]

  [[ 0  0  0  0  0]
   [ 0 28 29 30  0]
   [ 0 31 32 33  0]
   [ 0 34 35 36  0]
   [ 0  0  0  0  0]]]]


### Slow Convolution Layer: Forward

In [78]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

# This is a PyTorch Convolution example to be used to check if the convolution implemented in both slow and fast approaches are correct

class CustomConv(nn.Module):
    def __init__(self, kernel: torch.Tensor, bias: torch.Tensor = None, 
                 stride=1, padding=0):
        super().__init__()
        out_ch, in_ch, k_h, k_w = kernel.shape
        self.stride = stride
        self.padding = padding
        
        self.conv = nn.Conv2d(in_channels=in_ch,
                              out_channels=out_ch,
                              kernel_size=(k_h, k_w),
                              stride=stride,
                              padding=padding,
                              bias=(bias is not None))
        with torch.no_grad():
            self.conv.weight.copy_(kernel)
            if bias is not None:
                self.conv.bias.copy_(bias)

        self.conv.weight.requires_grad_(False)
        if bias is not None:
            self.conv.bias.requires_grad_(False)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return F.relu(self.conv(x))

def Slow_ReLU_Conv(img,ker,bias=np.array(0),pad=0,stride=1,applyReLU=True):
    if applyReLU: # Forward case
        out_ch, in_ch, k_width, k_height = ker.shape
        nk_channel = out_ch
    else: # Backward case
        in_ch, out_ch, k_width, k_height = ker.shape
        nk_channel = in_ch

    # bias has shape out_ch, 1, 1. It's a scalar value for each channel broadcasted to the kernel's width and height
    # number of channels taken in input by the kernel 'in_ch' 
    # must be the same as the number of channels of the image 'channels'

    img = np.pad(img,((0,0),(0,0),(pad,pad),(pad,pad)))
    n_images, channels, i_width, i_height = img.shape
    ni_height = int(((i_height - k_height) / stride) + 1) # new image height # Padding is already added
    ni_width = int(((i_width - k_width) / stride) + 1) # new image width
    ni = np.zeros((n_images, out_ch, ni_height, ni_width)).astype(np.float32) # new image

    if in_ch != channels:
        raise ValueError(f"number of channels taken in input by the kernel ({in_ch}) must be the same as the number of channels of the image ({channels})")

    for one_img in range(n_images):
        for one_k_channel in range(nk_channel):
            for i_nih in range(ni_height): # which cycles row by row of the new image
                for i_niw in range(ni_width): # which cycles column by column of the new image
                    current_sum = 0.0 # convolution sum for the specific output cell
                    # Convolution cycles
                    for channel in range(channels): # channels == in_ch
                        for i_kh in range(k_height):
                            input_y = (i_nih * stride) + i_kh # get the y location, the height
                            for i_kw in range(k_width):
                                input_x = (i_niw * stride) + i_kw # get the x location, the width
                                # check that everything stays in the measures
                                if 0 <= input_y < i_height and 0 <= input_x < i_width:
                                    input_val = img[one_img, channel, input_y, input_x]
                                    kernel_val = ker[one_k_channel, channel, i_kh, i_kw]
                                    current_sum += (input_val * kernel_val).astype(np.float32)
                    ni[one_img, one_k_channel, i_nih, i_niw] = current_sum
    if bias.all() != 0:
        bias = bias.reshape(bias.shape[0],1,1)
        if bias.shape[0] != out_ch:
            raise ValueError(f"bias dimension ({bias.shape[0]}) doesn't match kernel's number of channels ({out_ch})")
        ni = ni + bias
    ni = ni.astype(np.float32)
    if applyReLU:
        ni = np.maximum(0, ni)
        mask = ni.copy()
        mask[mask > 0] = 1
        return ni,mask
    else:
        return ni
#-------------------------------------------- Examples --------------------------------------------------------
img = np.arange(1,3*3+1).reshape(1,1,3,3).astype(np.float32)
print("-------img-------")
print(img)
ker = np.arange(1,8+1).reshape(2,1,2,2)
print("-------ker-------")
print(ker)
bias = np.array([1,2]).reshape(2,1,1)
res,mask = Slow_ReLU_Conv(img,ker,bias,pad=1,stride=2)
print("-------Conv Slow-------")
print(res)
# print("------mask-------")
# print(mask)


my_kernel = torch.from_numpy(ker).float()

my_bias = torch.from_numpy(np.array([1,2])).float()

modelC = CustomConv(kernel=my_kernel,bias=my_bias, stride=2, padding=1)

# input di prova (batch=1, canali=1, H=5, W=5)
x = torch.from_numpy(img)
y = modelC(x)
print("-------Conv PyTorch-------")
print(y)

-------img-------
[[[[1. 2. 3.]
   [4. 5. 6.]
   [7. 8. 9.]]]]
-------ker-------
[[[[1 2]
   [3 4]]]


 [[[5 6]
   [7 8]]]]
-------Conv Slow-------
[[[[  5.  19.]
   [ 37.  78.]]

  [[ 10.  40.]
   [ 82. 191.]]]]
-------Conv PyTorch-------
tensor([[[[  5.,  19.],
          [ 37.,  78.]],

         [[ 10.,  40.],
          [ 82., 191.]]]])


### Fast Convolution Layer: Forward

In [6]:
def Fast_ReLU_Conv(batch_of_images,kernel,bias,pad=0,stride=1):
    kc, ac, kw, kh = kernel.shape # number of kernels, number of input channels, kernel width and kernel height
    # im2col: Window creation
    batch_of_images = np.pad(batch_of_images,((0,0),(0,0),(pad,pad),(pad,pad)))
    bs, nc, iw, ih = batch_of_images.shape # batch of images' number of images, number of channels, single image's width, single images's height
    window_m = np.lib.stride_tricks.sliding_window_view(batch_of_images,(1,nc,kw,kh))[:,:,::stride,::stride].reshape((-1,(kw*kh*nc))) # window matrix
    # Convolution
    kernel = kernel.reshape((-1,(kw*kh*nc))).transpose(1,0)
    c_m = (window_m @ kernel).astype(np.float32) # convolved image matrix
    # ReLU activation
    nih = int(((ih-kh) / stride) + 1) # new image height # Padding is already added
    niw = int(((iw-kw) / stride) + 1) # new image width
    # First operate a reshape keeping spatial ordering, which has channels at the end
    output_temp = c_m.reshape(bs, nih, niw, kc)
    # Transpose to have input in shapes (batch, output_channel, height, width)
    reshaped_correct_order = output_temp.transpose(0,3,1,2)
    reshaped_correct_order = (reshaped_correct_order + bias.reshape(1,-1,1,1)).astype(np.float32)
    reshaped_correct_order = np.maximum(0,reshaped_correct_order)
    mask = np.copy(reshaped_correct_order)
    mask[mask>0]=1
    return reshaped_correct_order,mask



img = np.arange(1,2*3*3+1).reshape(1,2,3,3).astype(np.float32)
# print("-------img-------")
# print(img)
ker = np.arange(1,16+1).reshape(2,2,2,2)
# print("-------ker-------")
# print(ker)
bias = np.array([1,2]).reshape(2,1,1)
res,mask = Slow_ReLU_Conv(img,ker,bias,pad=0,stride=1)
print("-------Conv Slow-------")
print(res)
X_c,mask = Fast_ReLU_Conv(img,ker,bias,pad = 0,stride=1)
print("-------Conv Fast-------")
print(X_c)
res,mask = Slow_ReLU_Conv(res,ker,bias,pad=0,stride=1)
print("-------Conv Slow-------")
print(res)
X_c,mask = Fast_ReLU_Conv(X_c,ker,bias,pad = 0,stride=1)
print("-------Conv Fast-------")
print(X_c)

-------Conv Slow-------
[[[[ 357.  393.]
   [ 465.  501.]]

  [[ 838.  938.]
   [1138. 1238.]]]]
-------Conv Fast-------
[[[[ 357.  393.]
   [ 465.  501.]]

  [[ 838.  938.]
   [1138. 1238.]]]]
-------Conv Slow-------
[[[[32231.]]

  [[79176.]]]]
-------Conv Fast-------
[[[[32231.]]

  [[79176.]]]]


### Slow Convolution Layer: Forward

**Actors:**
1. W is the kernel
2. $\delta$ is the gradient
3. x is the input to the convolution layer during forward
4. b is the bias

**Steps:**

- **Derive delta**

Deriving delta with respect to ReLU activation consists in the hadamard product (element-wise product) of the gradient ($\delta$) and the mask obtained at the forward step, that is, all the elements in the convolved image greater than zero are put to one, the rest is zero.
$$
\delta^{(i)} = \delta_{\text{flat reshaped}} \cdot \text{mask}
$$

- **Gradient with respect to W**:

$$
\frac{\partial L}{\partial W^{(i)}} = \text{Convolution}(x^{(i)}, \delta)
$$
This convolution creates a matrix for every channel of input image $x^{i}$ and for every channel of output image $\delta$, thus resulting in the correct number of channels

- **Gradient w.r.t. the input \( x \)** (To go to the preceding layer):

$$
\delta^{(i-1)} = \text{Full\_Convolution}(\delta^{(i)}, W^{(i)})
$$
Could also use Transposed Convolution, which is also known as *fractionally strided convolution*

<img src="IMAGES\tc2.png" style="width:600px; left:1000px">

- **Gradient w.r.t the bias**

Since the bias is added equally across the spatial dimensions of each output channel, the gradient is the sum of all elements in each output channel:

$$
\frac{\partial L}{\partial b^{(i)}_c} = \sum_{h,w} \delta^{(i)}_{c,h,w}
$$

For batched inputs, sum also across the batch dimension:

$$
\frac{\partial L}{\partial b^{(i)}_c} = \sum_{n,h,w} \delta^{(i)}_{n,c,h,w}
$$

In [77]:
def Slow_ReLU_FullConv(img,d_img,ker,mask,pad=0,stride=1):
    """
    Performs the backward pass of the convolution layer. It takes the original image, 
    the gradient image, and then the kernel, padding and stride used in the convolution. Also the mask is needed to perform the ReLU operation
    It returns the gradient w.r.t. the Original Image to back propagate and the gradient of the kernel
    """ 

    out_ch, _, k_width, k_height = ker.shape
    
    n_images, channels, i_width, i_height = img.shape

    ni_height = (i_height-1)*stride-(2*pad)+k_height # new image height
    ni_width =  (i_width-1)*stride-(2*pad)+k_width# new image width
    height_to_pad = ni_height-i_height
    width_to_pad = ni_width-i_width
    d_img = np.multiply(d_img,mask)
    d_img = np.pad(d_img,((0,0),(0,0),(width_to_pad,width_to_pad),(height_to_pad,height_to_pad)))
    ni = np.zeros((n_images, channels, i_height, i_width)).astype(np.float32) # new image
    # Gradient of the image
    for one_img in range(n_images):
        for channel in range(channels):
            for i_nih in range(i_height): # which cycles row by row of the new image
                for i_niw in range(i_width): # which cycles column by column of the new image
                    current_sum = 0.0 # convolution sum for the specific output cell
                    # Convolution cycles
                    for one_k_channel in range(out_ch): # channels == out_ch
                        for i_kh in range(k_height):
                            input_y = (i_nih * stride) + i_kh # get the y location, the height
                            for i_kw in range(k_width):
                                input_x = (i_niw * stride) + i_kw # get the x location, the width
                                # check that everything stays in the measures
                                if 0 <= input_y < i_height and 0 <= input_x < i_width:
                                    input_val = d_img[one_img, one_k_channel, input_y, input_x]
                                    kernel_val = ker[one_k_channel,channel, i_kh, i_kw]
                                    current_sum += (input_val * kernel_val).astype(np.float32)
                    ni[one_img, channel, i_nih, i_niw] = current_sum
    new_kernel = Slow_ReLU_Conv(img,d_img,pad=pad,stride=stride,applyReLU=False)
    return ni,new_kernel

img = np.arange(1,17).reshape(1,1,4,4)
ker = np.arange(1,9).reshape(2,1,2,2)
bias = np.array([1,1])
d_img,mask=Slow_ReLU_Conv(img,ker,bias)
print("-------------d_img--------------")
d_img = d_img - 2
print(d_img)
print(d_img.shape)
print("--------------------------------")
a,b = Slow_ReLU_FullConv(img,d_img,ker,mask)
print(a)
print(b)

c=Slow_ReLU_Conv(img,d_img,applyReLU=False)
print(c)


-------------d_img--------------
[[[[ 43.  53.  63.]
   [ 83.  93. 103.]
   [123. 133. 143.]]

  [[ 99. 125. 151.]
   [203. 229. 255.]
   [307. 333. 359.]]]]
(1, 2, 3, 3)
--------------------------------
[[[[ 964. 2034. 2494. 1246.]
   [2636. 5268. 6044. 2912.]
   [4332. 8372. 9148. 4320.]
   [2088. 3922. 4238. 1938.]]]]
[]
[[[[ 6042.  6879.]
   [ 9390. 10227.]]

  [[    0.     0.]
   [    0.     0.]]]]


### Slow Convolution Layer: Forward

### MLP Layer: Forward

In [8]:
def softmax(x):
    e_x = np.exp(x - np.max(x,axis=-1,keepdims=True))  # for numerical stability
    return e_x / np.sum(e_x,axis=-1,keepdims=True)

def ReLU_SoftMax_FullyConnected(input_array,w1,b1,w2,b2):
    fl = (input_array @ w1)+b1 # first layer
    fa = np.maximum(0,fl) # first activation: ReLU
    sl = (fa @ w2)+b2 # second layer
    sa = softmax(sl) # second activation: SoftMax
    return fl,fa,sl,sa

#print(softmax([1,2,3,100000]))
#print(softmax_no_NS([1,2,3,1000]))
#r = np.array(np.array([1,2,777,2]))
#print(softmax(r))
#r = np.array((np.array([1,2,777,2]),np.array([1,2,777,2]),np.array([1,2,777,2])))
#print(softmax(r))

### Loss Function: Categorical Cross-Entropy

In [9]:
def crossEntropy(p,t):
    # p stands for prediction and t stands for true label
    # p = [0,0,1] and t = [1,0,0]
    p = p+(1/100000) # for numerical stability
    return -np.dot(t,np.log(p).T)

#c = [1,1000000000000000,1,1]
#c = softmax(c)
#print(c)
#c = crossEntropy(c,[0,1,0,0])
#print(c)

## Inference

In this section the three implementations will be compared in terms of time. Recall that all the predictions should be the same since the weights are the same.

In [ ]:
import time
from tqdm import tqdm

np_k1 = numpy_weights['k1'].astype(np.float32)
np_b_conv1 = numpy_weights['b_conv1'].astype(np.float32)
np_k2 = numpy_weights['k2'].astype(np.float32)
np_b_conv2 = numpy_weights['b_conv2'].astype(np.float32)
np_k3 = numpy_weights['k3'].astype(np.float32)
np_b_conv3 = numpy_weights['b_conv3'].astype(np.float32)
np_w1 = numpy_weights['w1'].astype(np.float32)
np_b1 = numpy_weights['b1'].astype(np.float32)
np_w2 = numpy_weights['w2'].astype(np.float32)
np_b2 = numpy_weights['b2'].astype(np.float32)

dict_times={}
dict_times["ctorch"]=[]
dict_times["cslow"]=[]
dict_times["cfast"]=[]

dict_pred={}
dict_pred["ctorch"]=[]
dict_pred["cslow"]=[]
dict_pred["cfast"]=[]

#length = test_labels.shape[0]
length = 100

for i in tqdm(range(length),desc=" Inferring..."):
    c0 = test_images[i].reshape(1,1,28,28).astype(np.float32)
    torch_c0 = torch.from_numpy(c0).float()
    ############### CNN PyTorch Implementation ##################
    start_time = time.time()
    outputs = model(torch_c0)
    end_time = time.time()
    _, predicted1 = torch.max(outputs.data, 1)
    dict_times["ctorch"].append(end_time-start_time)
    dict_pred["ctorch"].append(np.array(predicted1))
    ############### CNN Slow Implementation #####################
    start_time = time.time()
    c1s,mask1s = Slow_ReLU_Conv(c0.astype(np.float32),np_k1,np_b_conv1,pad=1,stride=2)
    c2s,mask2s = Slow_ReLU_Conv(c1s.astype(np.float32),np_k2,np_b_conv2,pad=1,stride=2)
    c3s,mask3s = Slow_ReLU_Conv(c2s.astype(np.float32),np_k3,np_b_conv3,pad=1,stride=2)
    imlps = c3s.reshape(1,-1)
    _,_,_,res = ReLU_SoftMax_FullyConnected(imlps,np_w1,np_b1,np_w2,np_b2)
    predicted2 = np.argmax(res,1)
    end_time = time.time()
    dict_times["cslow"].append(end_time-start_time)
    dict_pred["cslow"].append(np.array(predicted2))
    ############### CNN Fast Implementation #####################
    start_time = time.time()
    c1f,mask1f = Fast_ReLU_Conv(c0.astype(np.float32),np_k1,np_b_conv1,pad=1,stride=2)
    c2f,mask2f = Fast_ReLU_Conv(c1f.astype(np.float32),np_k2,np_b_conv2,pad=1,stride=2)
    c3f,mask3f = Fast_ReLU_Conv(c2f.astype(np.float32),np_k3,np_b_conv3,pad=1,stride=2)
    imlpf = c3f.reshape(1,-1)
    _,_,_,res = ReLU_SoftMax_FullyConnected(imlpf,np_w1,np_b1,np_w2,np_b2)
    predicted3 = np.argmax(res,1)
    end_time = time.time()
    dict_times["cfast"].append(end_time-start_time)
    dict_pred["cfast"].append(np.array(predicted3))
    #print(f"predictions: t: {predicted1}, s: {predicted2}, f: {predicted3}\r") # Unfortunately \r doesn't rewrite on the same line


 Inferring...:   1%|          | 1/100 [00:04<07:44,  4.69s/it]

predictions: t: tensor([7]), s: [7], f: [7]


 Inferring...:   2%|▏         | 2/100 [00:08<06:56,  4.25s/it]

predictions: t: tensor([2]), s: [2], f: [2]


 Inferring...:   3%|▎         | 3/100 [00:13<07:19,  4.53s/it]

predictions: t: tensor([1]), s: [1], f: [1]


 Inferring...:   4%|▍         | 4/100 [00:17<06:54,  4.32s/it]

predictions: t: tensor([0]), s: [0], f: [0]


 Inferring...:   5%|▌         | 5/100 [00:22<07:00,  4.43s/it]

predictions: t: tensor([4]), s: [4], f: [4]


 Inferring...:   6%|▌         | 6/100 [00:26<06:50,  4.36s/it]

predictions: t: tensor([1]), s: [1], f: [1]


 Inferring...:   7%|▋         | 7/100 [00:31<06:56,  4.48s/it]

predictions: t: tensor([4]), s: [4], f: [4]


 Inferring...:   8%|▊         | 8/100 [00:35<06:46,  4.41s/it]

predictions: t: tensor([9]), s: [9], f: [9]


 Inferring...:   9%|▉         | 9/100 [00:39<06:35,  4.34s/it]

predictions: t: tensor([6]), s: [6], f: [6]


 Inferring...:  10%|█         | 10/100 [00:44<06:41,  4.46s/it]

predictions: t: tensor([9]), s: [9], f: [9]


 Inferring...:  11%|█         | 11/100 [00:48<06:29,  4.38s/it]

predictions: t: tensor([0]), s: [0], f: [0]


 Inferring...:  12%|█▏        | 12/100 [00:53<06:40,  4.55s/it]

predictions: t: tensor([6]), s: [6], f: [6]


 Inferring...:  13%|█▎        | 13/100 [00:57<06:31,  4.50s/it]

predictions: t: tensor([9]), s: [9], f: [9]


 Inferring...:  14%|█▍        | 14/100 [01:02<06:36,  4.61s/it]

predictions: t: tensor([0]), s: [0], f: [0]


 Inferring...:  15%|█▌        | 15/100 [01:06<06:23,  4.51s/it]

predictions: t: tensor([1]), s: [1], f: [1]


 Inferring...:  16%|█▌        | 16/100 [01:11<06:26,  4.60s/it]

predictions: t: tensor([5]), s: [5], f: [5]


 Inferring...:  17%|█▋        | 17/100 [01:16<06:16,  4.53s/it]

predictions: t: tensor([9]), s: [9], f: [9]


 Inferring...:  18%|█▊        | 18/100 [01:20<06:14,  4.56s/it]

predictions: t: tensor([7]), s: [7], f: [7]


 Inferring...:  19%|█▉        | 19/100 [01:24<05:55,  4.39s/it]

predictions: t: tensor([3]), s: [3], f: [3]


 Inferring...:  20%|██        | 20/100 [01:29<06:02,  4.53s/it]

predictions: t: tensor([4]), s: [4], f: [4]


 Inferring...:  21%|██        | 21/100 [01:33<05:44,  4.36s/it]

predictions: t: tensor([9]), s: [9], f: [9]


 Inferring...:  22%|██▏       | 22/100 [01:38<06:01,  4.64s/it]

predictions: t: tensor([6]), s: [6], f: [6]


 Inferring...:  23%|██▎       | 23/100 [01:43<05:48,  4.53s/it]

predictions: t: tensor([6]), s: [6], f: [6]


 Inferring...:  24%|██▍       | 24/100 [01:48<05:53,  4.65s/it]

predictions: t: tensor([5]), s: [5], f: [5]


 Inferring...:  25%|██▌       | 25/100 [01:52<05:42,  4.57s/it]

predictions: t: tensor([4]), s: [4], f: [4]


 Inferring...:  26%|██▌       | 26/100 [01:57<05:47,  4.70s/it]

predictions: t: tensor([0]), s: [0], f: [0]


 Inferring...:  27%|██▋       | 27/100 [02:01<05:31,  4.53s/it]

predictions: t: tensor([7]), s: [7], f: [7]


 Inferring...:  28%|██▊       | 28/100 [02:06<05:35,  4.66s/it]

predictions: t: tensor([4]), s: [4], f: [4]


 Inferring...:  29%|██▉       | 29/100 [02:10<05:26,  4.60s/it]

predictions: t: tensor([0]), s: [0], f: [0]


 Inferring...:  30%|███       | 30/100 [02:15<05:26,  4.66s/it]

predictions: t: tensor([1]), s: [1], f: [1]


 Inferring...:  31%|███       | 31/100 [02:19<05:07,  4.46s/it]

predictions: t: tensor([3]), s: [3], f: [3]


 Inferring...:  32%|███▏      | 32/100 [02:24<05:10,  4.57s/it]

predictions: t: tensor([1]), s: [1], f: [1]


 Inferring...:  33%|███▎      | 33/100 [02:28<04:53,  4.38s/it]

predictions: t: tensor([3]), s: [3], f: [3]


 Inferring...:  34%|███▍      | 34/100 [02:32<04:50,  4.40s/it]

predictions: t: tensor([4]), s: [4], f: [4]


 Inferring...:  35%|███▌      | 35/100 [02:37<04:42,  4.35s/it]

predictions: t: tensor([7]), s: [7], f: [7]


 Inferring...:  36%|███▌      | 36/100 [02:41<04:33,  4.28s/it]

predictions: t: tensor([2]), s: [2], f: [2]


 Inferring...:  37%|███▋      | 37/100 [02:45<04:37,  4.40s/it]

predictions: t: tensor([7]), s: [7], f: [7]


 Inferring...:  38%|███▊      | 38/100 [02:50<04:25,  4.28s/it]

predictions: t: tensor([1]), s: [1], f: [1]


 Inferring...:  39%|███▉      | 39/100 [02:54<04:28,  4.39s/it]

predictions: t: tensor([2]), s: [2], f: [2]


 Inferring...:  40%|████      | 40/100 [02:58<04:17,  4.29s/it]

predictions: t: tensor([1]), s: [1], f: [1]


 Inferring...:  41%|████      | 41/100 [03:03<04:14,  4.31s/it]

predictions: t: tensor([1]), s: [1], f: [1]


 Inferring...:  42%|████▏     | 42/100 [03:07<04:12,  4.35s/it]

predictions: t: tensor([7]), s: [7], f: [7]


 Inferring...:  43%|████▎     | 43/100 [03:11<04:05,  4.31s/it]

predictions: t: tensor([4]), s: [4], f: [4]


 Inferring...:  44%|████▍     | 44/100 [03:16<04:08,  4.44s/it]

predictions: t: tensor([2]), s: [2], f: [2]


 Inferring...:  45%|████▌     | 45/100 [03:20<04:00,  4.37s/it]

predictions: t: tensor([3]), s: [3], f: [3]


 Inferring...:  46%|████▌     | 46/100 [03:25<04:01,  4.48s/it]

predictions: t: tensor([5]), s: [5], f: [5]


 Inferring...:  47%|████▋     | 47/100 [03:29<03:54,  4.42s/it]

predictions: t: tensor([1]), s: [1], f: [1]


 Inferring...:  48%|████▊     | 48/100 [03:34<04:03,  4.69s/it]

predictions: t: tensor([2]), s: [2], f: [2]


 Inferring...:  49%|████▉     | 49/100 [03:39<03:51,  4.55s/it]

predictions: t: tensor([4]), s: [4], f: [4]


 Inferring...:  50%|█████     | 50/100 [03:43<03:49,  4.59s/it]

predictions: t: tensor([4]), s: [4], f: [4]


 Inferring...:  51%|█████     | 51/100 [03:47<03:37,  4.44s/it]

predictions: t: tensor([6]), s: [6], f: [6]


 Inferring...:  52%|█████▏    | 52/100 [03:52<03:37,  4.54s/it]

predictions: t: tensor([3]), s: [3], f: [3]


 Inferring...:  53%|█████▎    | 53/100 [03:56<03:26,  4.40s/it]

predictions: t: tensor([5]), s: [5], f: [5]


 Inferring...:  54%|█████▍    | 54/100 [04:01<03:22,  4.39s/it]

predictions: t: tensor([5]), s: [5], f: [5]


 Inferring...:  55%|█████▌    | 55/100 [04:05<03:17,  4.39s/it]

predictions: t: tensor([6]), s: [6], f: [6]


 Inferring...:  56%|█████▌    | 56/100 [04:09<03:09,  4.30s/it]

predictions: t: tensor([0]), s: [0], f: [0]


 Inferring...:  57%|█████▋    | 57/100 [04:14<03:10,  4.42s/it]

predictions: t: tensor([4]), s: [4], f: [4]


 Inferring...:  58%|█████▊    | 58/100 [04:18<02:59,  4.27s/it]

predictions: t: tensor([1]), s: [1], f: [1]


 Inferring...:  59%|█████▉    | 59/100 [04:22<02:59,  4.39s/it]

predictions: t: tensor([9]), s: [9], f: [9]


 Inferring...:  60%|██████    | 60/100 [04:27<02:52,  4.32s/it]

predictions: t: tensor([5]), s: [5], f: [5]


 Inferring...:  61%|██████    | 61/100 [04:31<02:51,  4.40s/it]

predictions: t: tensor([7]), s: [7], f: [7]


 Inferring...:  62%|██████▏   | 62/100 [04:36<02:47,  4.41s/it]

predictions: t: tensor([8]), s: [8], f: [8]


 Inferring...:  63%|██████▎   | 63/100 [04:40<02:39,  4.32s/it]

predictions: t: tensor([9]), s: [9], f: [9]


 Inferring...:  64%|██████▍   | 64/100 [04:45<02:40,  4.47s/it]

predictions: t: tensor([3]), s: [3], f: [3]


 Inferring...:  65%|██████▌   | 65/100 [04:49<02:30,  4.31s/it]

predictions: t: tensor([7]), s: [7], f: [7]


 Inferring...:  66%|██████▌   | 66/100 [04:53<02:32,  4.48s/it]

predictions: t: tensor([4]), s: [4], f: [4]


 Inferring...:  67%|██████▋   | 67/100 [04:58<02:24,  4.38s/it]

predictions: t: tensor([6]), s: [6], f: [6]


 Inferring...:  68%|██████▊   | 68/100 [05:02<02:24,  4.53s/it]

predictions: t: tensor([4]), s: [4], f: [4]


 Inferring...:  69%|██████▉   | 69/100 [05:06<02:15,  4.37s/it]

predictions: t: tensor([3]), s: [3], f: [3]


 Inferring...:  70%|███████   | 70/100 [05:11<02:13,  4.44s/it]

predictions: t: tensor([0]), s: [0], f: [0]


 Inferring...:  71%|███████   | 71/100 [05:16<02:09,  4.45s/it]

predictions: t: tensor([7]), s: [7], f: [7]


 Inferring...:  72%|███████▏  | 72/100 [05:21<02:09,  4.62s/it]

predictions: t: tensor([0]), s: [0], f: [0]


 Inferring...:  73%|███████▎  | 73/100 [05:25<02:00,  4.47s/it]

predictions: t: tensor([2]), s: [2], f: [2]


 Inferring...:  74%|███████▍  | 74/100 [05:29<01:57,  4.51s/it]

predictions: t: tensor([9]), s: [9], f: [9]


 Inferring...:  75%|███████▌  | 75/100 [05:33<01:50,  4.41s/it]

predictions: t: tensor([1]), s: [1], f: [1]


 Inferring...:  76%|███████▌  | 76/100 [05:38<01:47,  4.48s/it]

predictions: t: tensor([7]), s: [7], f: [7]


 Inferring...:  77%|███████▋  | 77/100 [05:43<01:44,  4.52s/it]

predictions: t: tensor([3]), s: [3], f: [3]


 Inferring...:  78%|███████▊  | 78/100 [05:48<01:41,  4.63s/it]

predictions: t: tensor([2]), s: [2], f: [2]


 Inferring...:  79%|███████▉  | 79/100 [05:52<01:36,  4.60s/it]

predictions: t: tensor([9]), s: [9], f: [9]


 Inferring...:  80%|████████  | 80/100 [05:57<01:34,  4.72s/it]

predictions: t: tensor([7]), s: [7], f: [7]


 Inferring...:  81%|████████  | 81/100 [06:01<01:26,  4.55s/it]

predictions: t: tensor([7]), s: [7], f: [7]


 Inferring...:  82%|████████▏ | 82/100 [06:06<01:23,  4.62s/it]

predictions: t: tensor([6]), s: [6], f: [6]


 Inferring...:  83%|████████▎ | 83/100 [06:10<01:15,  4.47s/it]

predictions: t: tensor([2]), s: [2], f: [2]


 Inferring...:  84%|████████▍ | 84/100 [06:15<01:11,  4.46s/it]

predictions: t: tensor([7]), s: [7], f: [7]


 Inferring...:  85%|████████▌ | 85/100 [06:19<01:07,  4.48s/it]

predictions: t: tensor([8]), s: [8], f: [8]


 Inferring...:  86%|████████▌ | 86/100 [06:23<01:00,  4.35s/it]

predictions: t: tensor([4]), s: [4], f: [4]


 Inferring...:  87%|████████▋ | 87/100 [06:28<00:58,  4.47s/it]

predictions: t: tensor([7]), s: [7], f: [7]


 Inferring...:  88%|████████▊ | 88/100 [06:32<00:51,  4.31s/it]

predictions: t: tensor([3]), s: [3], f: [3]


 Inferring...:  89%|████████▉ | 89/100 [06:37<00:50,  4.57s/it]

predictions: t: tensor([6]), s: [6], f: [6]


 Inferring...:  90%|█████████ | 90/100 [06:41<00:44,  4.40s/it]

predictions: t: tensor([1]), s: [1], f: [1]


 Inferring...:  91%|█████████ | 91/100 [06:46<00:40,  4.52s/it]

predictions: t: tensor([3]), s: [3], f: [3]


 Inferring...:  92%|█████████▏| 92/100 [06:50<00:35,  4.42s/it]

predictions: t: tensor([6]), s: [6], f: [6]


 Inferring...:  93%|█████████▎| 93/100 [06:55<00:32,  4.64s/it]

predictions: t: tensor([9]), s: [9], f: [9]


 Inferring...:  94%|█████████▍| 94/100 [06:59<00:26,  4.47s/it]

predictions: t: tensor([3]), s: [3], f: [3]


 Inferring...:  95%|█████████▌| 95/100 [07:03<00:21,  4.40s/it]

predictions: t: tensor([1]), s: [1], f: [1]


 Inferring...:  96%|█████████▌| 96/100 [07:08<00:17,  4.38s/it]

predictions: t: tensor([4]), s: [4], f: [4]


 Inferring...:  97%|█████████▋| 97/100 [07:12<00:12,  4.33s/it]

predictions: t: tensor([1]), s: [1], f: [1]


 Inferring...:  98%|█████████▊| 98/100 [07:17<00:08,  4.48s/it]

predictions: t: tensor([7]), s: [7], f: [7]


 Inferring...:  99%|█████████▉| 99/100 [07:21<00:04,  4.36s/it]

predictions: t: tensor([6]), s: [6], f: [6]


 Inferring...: 100%|██████████| 100/100 [07:26<00:00,  4.47s/it]

predictions: t: tensor([9]), s: [9], f: [9]


Check that outputs of Slow Approach and Fast Approach have the same results

In [ ]:
print(c1f.shape)
print(c1s.shape)
a,b,c,d = c1f.shape
correct = 0
total = 0
decimals=3
for i in range(a):
    for j in range(b):
        for k in range(c):
            for l in range(d):
                r_c1f = round(c1f[i,j,k,l],decimals)
                r_c1s = round(c1s[i,j,k,l],decimals)
                if r_c1f == r_c1s:
                    correct+=1
                else:
                    print(f"f: {r_c1f}, s: {r_c1s}")
                total+=1
print(f"correct: {100*correct/total}")


(1, 32, 14, 14)
(1, 32, 14, 14)


TypeError: type numpy.ndarray doesn't define __round__ method

Check that all three approaches output the same predictions and measure the time performance

In [ ]:
correct_prediction = 0
for i in range(length):
    t = np.array(dict_pred["ctorch"][i])
    s = np.array(dict_pred["cslow"][i])
    f = np.array(dict_pred["cfast"][i])
    if t == s and t == f:
        correct+=1
print(f"correct: {100*correct_prediction/length}")
# Since the predictions are the same, so are the performances
print(f"Average forward execution time in seconds: t: {round(sum(dict_times['ctorch'])/length,4)}, s: {round(sum(dict_times['cslow']),4)/length}, f: {round(sum(dict_times['cfast']),4)/length}")
print("Where implementations are:\nt: PyTorch\ns: Slow\nf: Fast")


correct: 0.0
Average forward execution time in seconds: t: 0.0017, s: 4.462299, f: 0.001478
Where implementations are:
t: PyTorch
s: Slow
f: Fast


In [26]:
import numpy as np
import torch
tensorr = torch.from_numpy(np.array([5,1]))
h = int(tensorr)
h

ValueError: only one element tensors can be converted to Python scalars