# CNN Inference with NumPy
In the classic CNN behaviour, we are given an image, the kernel passes over each subset of the image and for each subset it computes the sum of element-wise products. If done with vanilla Python, this procedure results in a slow execution. In PyTorch the problem is solved thanks to the framework given by the module itself. The idea of using numpy consists in transforming the given image in a matrix where each row is composed by one of the subset of the image interested in the convolution with the kernel, then vectorize the kernel and then perform the convolution step by simply operating a dot product between the subset and the kernel. This operation is fast in numpy, which is the Python module responsible for numeric computations. This approach is good but it introduces redundancy in data. A tradeoff between memory and cpu

# provare jax

`PLACEHOLDER`

## Theory

### Kernel Multiplication
Convolving an image of dimensions 800 x 600 x 3 where 3 is the number of channels (one for red, one for green and one for blue) with a kernel of size 2x2x3 outputs an image of dimensions 799x599x1. Kernel's number of channels must match the number of channels of the input image. Therefore if i want, for example, to obtain a color image as the result of a convolution, i would need to convolve the input image with three kernels of three channels. Another way to see this is that the number of kernels i use in the convolution will become the number of channels for the output image 

`X = X[::3,:]` means "Please select the first three rows of matrix X and return them"

### Channels Problem: How to consider multiple channels:
taking the previous matrix as an example, and adding a channel where every number is the corresponding of the first channel but *100 we obtain:
01,02,05,06,101,102,105,106
Which means just append the next channel's corresponding flattened window to the previous one

### Batch Problem: How to consider multiple images:
just add the obtained windows at the end of the ones of the previous image, so instead of having a 5 rows 9 columns matrix of windows the result will be a matrix of 10 rows and 9 columns.

### Final input management
The more images can be stacked in the input, the faster the training will be, therefore the stack dimension must be taken into account. If the desire is to manage stacks of 8, 800x600 resolution color images (numbers were chosen so that they are better recognizable) with a 5x4 kernel, the function to create windows will have this shape:

`X = np.random.rand(8*3*800*600).reshape(8,3,800,600)`

`y = np.lib.stride_tricks.sliding_window_view(X,(1,3,5,4)).reshape(-1,(3*5*4))`

Which translates in:

`y = np.lib.stride_tricks.sliding_window_view(X,(1,CHANNEL_SIZE,KERNEL_WIDTH,KERNEL_HEIGHT))`

`y = y.reshape(-1,(CHANNEL_SIZE*KERNEL_WIDTH*KERNEL_HEIGHT))`

## Trials

In [1]:
import numpy as np
trials = True
def tprint(value):
    print(value) if trials else print()

### Inefficient Max Pooling

In [ ]:
def MaxPooling2DIneff(batch_of_images,win_size = 2, stride=2):
    # very inefficient... but it works...
    # it gives the same result as PyTorch's nn.MaxPool2d(kernel_size=2, stride=2)
    bs, nc, iw, ih = batch_of_images.shape # batch of images' number of images, number of channels, single image's width, single images's height
    #print(batch_of_images.shape)
    niw = round(iw/2) if iw % 2 == 0 else round(iw/2)-1
    nih = round(ih/2) if ih % 2 == 0 else round(ih/2)-1
    batch = []
    for bb in range(bs):
        channel=[]
        for cc in range(nc):
            y=[]
            for i in range(0,ih,stride):
                for j in range(0,iw,stride):
                    if (j+win_size)>iw:
                        continue
                    if (i+win_size)>ih:
                        continue
                    y.append(batch_of_images[bb,cc,i:(i+win_size),j:(j+win_size)].max())
            y=np.array(y).reshape(niw,nih)
            channel.append(y)
        batch.append(channel)
    return np.array(batch)
## this is an example
#X = np.arange(1,(6*6*2*2)+1).reshape(2,2,6,6)
#print(X)
#r=MaxPooling2D(X)
#print(r)

### Sliding Window View
To implement the im2col convolution approach, the first thing to do is creating the matrix of windows from the given image. This can be done with the helpful function `np.lib.stride_tricks.sliding_window_view(image,kernel_shape)` which exactly returns what this approach needs. In the next panel the functioning of this function will be done.


In [2]:
X = np.arange(1,(2*2*3*3)+1).reshape(2,2,3,3)
tprint(X)
tprint("desired result")
tprint("[1,2,4,5]")
tprint("[2,3,5,6]")
tprint("...")
tprint("correct one:")
y = np.lib.stride_tricks.sliding_window_view(X,(1,1,2,2))
tprint("wrong: after the first window there is the first window of the channel")
y = np.lib.stride_tricks.sliding_window_view(X,(1,1,2,2))

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]]

  [[10 11 12]
   [13 14 15]
   [16 17 18]]]


 [[[19 20 21]
   [22 23 24]
   [25 26 27]]

  [[28 29 30]
   [31 32 33]
   [34 35 36]]]]
desired result
[1,2,4,5]
[2,3,5,6]
...
correct one:
wrong: after the first window there is the first window of the channel


### Back from Pooling


In [43]:
X= np.zeros(4*4).reshape(4,4)
values = np.array([1,2,3,4]).reshape(2,2)
indices=np.array([0,1,3,2]).reshape(2,2)
print(X)
np.add.at(X,(indices,indices),values)
print(X)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 4. 0.]
 [0. 0. 0. 3.]]


In [40]:
import numpy as np
X = np.arange(1,17).reshape(4,4)
print(X)
stride = winSize = 2
small_X = np.array([6,5,6,7]).reshape(2,2)
small_dX = np.array([7,3,4,5]).reshape(2,2)
H_out,W_out = small_dX.shape
ind = np.array([3,0,2,1])
back_X = np.zeros(X.shape)
row = ind // winSize # if [3,3,3,3] // 2 returns [1,1,1,1]
col = ind % winSize # if [3,3,3,3] // 2 returns [1,1,1,1]
print("row,col")
print(row,col)
# it means, the first element must be at row one and col one starting from zero.
r_out_idx, c_out_idx = np.indices((H_out, W_out))
print("r_out_idx")
print(r_out_idx)
print("c_out_idx")
print(c_out_idx)

vert_start = r_out_idx * stride # Forma (bs, nc, H_out, W_out)
horiz_start = c_out_idx * stride # Forma (bs, nc, H_out, W_out)
print("vert_start")
print(vert_start)
print("horiz_start")
print(horiz_start)
#    c. Calcola le coordinate assolute finali in dA_prev
#       idx_row_in_window e idx_col_in_window devono essere "broadcastabili" o
#       avere la stessa forma di vert_start e horiz_start se non sono già piatte.
#       Poiché indices_flat era (bs*nc*H_out*W_out,), rimodelliamoli:
idx_row_in_window_reshaped = row.reshape(H_out, W_out)
idx_col_in_window_reshaped = col.reshape(H_out, W_out)
print("idx_row_in_window_reshaped")
print(idx_row_in_window_reshaped)
print("idx_col_in_window_reshaped")
print(idx_col_in_window_reshaped)
abs_row_coords = vert_start + idx_row_in_window_reshaped # Forma (bs, nc, H_out, W_out)
abs_col_coords = horiz_start + idx_col_in_window_reshaped # Forma (bs, nc, H_out, W_out)
print("abs_row_coords")
print(abs_row_coords)
print("abs_col_coords")
print(abs_col_coords)
# 4. Usa np.add.at per sommare i gradienti d_out nelle posizioni calcolate di dA_prev.
#    np.add.at(array, indici, valori_da_aggiungere)
#    Gli 'indici' devono essere una tupla di array di indici per ogni dimensione.
#    Tutti gli array in 'indici' e 'valori_da_aggiungere' devono essere broadcastabili
#    a una forma comune, o essere appiattiti in modo consistente.

#    Creiamo gli indici per np.add.at:
#    Tutti questi array (b_idx, ch_idx, abs_row_coords, abs_col_coords, d_out)
#    hanno già la stessa forma (bs, nc, H_out, W_out), quindi NumPy
#    li gestirà elemento per elemento quando usati come indici e valori.

indices_for_add_at = (
    abs_row_coords,         # Indici per la dimensione altezza di dA_prev
    abs_col_coords          # Indici per la dimensione larghezza di dA_prev
)
print("back_X")
print(back_X)
np.add.at(back_X, indices_for_add_at, small_dX)
print("back_X")
print(back_X)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
row,col
[1 0 1 0] [1 0 0 1]
r_out_idx
[[0 0]
 [1 1]]
c_out_idx
[[0 1]
 [0 1]]
vert_start
[[0 0]
 [2 2]]
horiz_start
[[0 2]
 [0 2]]
idx_row_in_window_reshaped
[[1 0]
 [1 0]]
idx_col_in_window_reshaped
[[1 0]
 [0 1]]
abs_row_coords
[[1 0]
 [3 2]]
abs_col_coords
[[1 2]
 [0 3]]
back_X
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
back_X
[[0. 0. 3. 0.]
 [0. 7. 0. 0.]
 [0. 0. 0. 5.]
 [4. 0. 0. 0.]]


### Striding
The next panel is devoted to explore the striding, achieved using the preceding, function along with the `[:,:,::2,::2]` construct that, respectively, leaves untouched the number of images in the batch and the number of channels, but selects one row every two and one column every two. rows and columns after the sliding window, uniquely identify one window.

In [3]:
X = np.arange(1,16*2+1).reshape(1,2,4,4)
tprint(X)
# basically [::2,::2] selects every two rows and every two columns, where in this case elements are 3 dimensional matrices of 2 by 2 so the 
# selection eliminates the desired elements, resulting in a stride 2 convolution 
y = np.lib.stride_tricks.sliding_window_view(X,(1,2,2,2))[:,:,::2,::2]
#y = np.lib.stride_tricks.as_strided(X,shape=(2,2),strides=[1,2,3,4])
tprint(y.reshape(-1,4))

[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]
   [13 14 15 16]]

  [[17 18 19 20]
   [21 22 23 24]
   [25 26 27 28]
   [29 30 31 32]]]]
[[ 1  2  5  6]
 [17 18 21 22]
 [ 3  4  7  8]
 [19 20 23 24]
 [ 9 10 13 14]
 [25 26 29 30]
 [11 12 15 16]
 [27 28 31 32]]


## Practice

### Imports

In [1]:
import numpy as np
import struct
import matplotlib.pyplot as plt
from tqdm import tqdm
import math

### Loading images and labels

In [47]:
def load_mnist_images(filename):
    with open(filename, 'rb') as f:
        # Leggi intestazione: magic number, numero immagini, righe, colonne
        magic, num_images, rows, cols = struct.unpack(">IIII", f.read(16))
        # Leggi tutti i pixel e convertili in array numpy
        images = np.frombuffer(f.read(), dtype=np.uint8)
        # Ridimensiona l'array in (num_images, rows, cols)
        images = images.reshape((num_images, rows, cols))
    return images

def load_mnist_labels(filename):
    with open(filename, 'rb') as f:
        magic, num_labels = struct.unpack(">II", f.read(8))
        labels = np.frombuffer(f.read(), dtype=np.uint8)
    return labels

images = load_mnist_images('MNIST/train-images-idx3-ubyte')
labels = load_mnist_labels('MNIST/train-labels-idx1-ubyte')

print(images.shape)  # (60000, 28, 28)
print(labels.shape)  # (60000,)
one_hot_labels = np.zeros(labels.shape[0]*10).reshape((labels.shape[0]),10)
for i in range(len(labels)):
    one_hot_labels[i][labels[i]]=1
labels = one_hot_labels

(60000, 28, 28)
(60000,)


## CNN Structure
The goal is achieving over 90% of accuracy with a simple structure, therefore this would be the set of layers:
- Convolutional Layer with 32 2x2 filters and ReLU activation: i: (B x C X 28 x 28), o: (B x 32 x 26 x 26)
- Max Pooling layer with 2x2 filter: i: (B x 32 x 26 x 26), o: (B x 32 x 13 x 13)
- Convolutional Layer with 32 2x2 filters and ReLU activation: i: (B x 13 x 13 x 32), o: (B x 11 x 11 x 64)
- Linear Fully Connected Layer with ReLU activation: i: (B x 7744), o: (B x 250)
- Linear Fully Connected Layer with Softmax activation: i: (B x 250), o: (B x 10)
- Cross-Entropy Loss: -sum(true_probability_distribution*log(predicted_probability_distribution))

where B is the batch_size and C is the number of channels, that for MNIST digits is just one, since they are greyscale images.

The idea is to reduce everything to a matrix-matrix multiplication which is super fast in NumPy, an optimized mathematical module for Python, by taking an image and create a matrix containing for each row the flattened window that would enter the convolution, as an example:
the first 2 flattened windows of this matrix:
01,02,03,04
05,06,07,08
09,10,11,12
13,14,15,16
for a kernel 2x2 of stride 1 are:
01,02,05,06
02,03,06,07



In [16]:
X = np.array([-4,0,4,2]).reshape(2,2)
reluX = np.maximum(0,X)
print(reluX)
BReluX=reluX
BReluX[BReluX>0]=1
print(BReluX)

[[0 0]
 [4 2]]
[[0 0]
 [1 1]]


### Convolution Layer

In [17]:
def ReLU_Convolution(batch_of_images,kernel,p=0,s=1):
    if len(kernel.shape)==2:
        kw, kh = kernel.shape # kernel width, height and number of channels
        iw, ih = batch_of_images.shape # batch of images' number of images, number of channels, single image's width, single images's height
        nc = 1
        window_m = np.lib.stride_tricks.sliding_window_view(batch_of_images,(kw,kh))[::s,::s].reshape(-1,(kw*kh*nc)) # window matrix
    else:
        ac, kc, kw, kh = kernel.shape # kernel width, height and number of channels
        bs, nc, iw, ih = batch_of_images.shape # batch of images' number of images, number of channels, single image's width, single images's height
        #p = 0 # padding
        #s = 1 # stride
        # im2col: Window creation
        window_m = np.lib.stride_tricks.sliding_window_view(batch_of_images,(1,nc,kw,kh))[:,:,::s,::s].reshape(-1,(kw*kh*nc)) # window matrix
    # Convolution
    kernel = kernel.reshape((kw*kh*nc),-1)
    c_m = window_m @ kernel # convolved image matrix
    # ReLU activation
    r_c_m = np.maximum(0,c_m) # convolved image matrix after ReLU activation
    
    niw = round(((iw-kw+(2*p))/s)+1) # new image width
    nih = round(((ih-kh+(2*p))/s)+1) # new image height
    
    # First operate a reshape keeping spatial ordering, which has channels at the end
    if len(kernel.shape)==2:
        reshaped_correct_order = r_c_m.reshape(nih, niw)
    else:
        output_temp = r_c_m.reshape(bs, nih, niw, kc)
        # Transpose to have input in shapes (batch, canali_output, height, width)
        reshaped_correct_order = output_temp.transpose(0, 3, 1, 2)
    return reshaped_correct_order


def ReLU_Convolution_Backward(batch_of_images,kernel,dX,p=0,s=1):
    print("This is the backward of the ReLU Convolution")
    if len(kernel.shape)==2:
        kw, kh = kernel.shape # kernel width, height and number of channels
        iw, ih = batch_of_images.shape # batch of images' number of images, number of channels, single image's width, single images's height
        nc = 1
        window_m = np.lib.stride_tricks.sliding_window_view(batch_of_images,(kw,kh))[::s,::s].reshape(-1,(kw*kh*nc)) # window matrix
        window_m_dx = np.lib.stride_tricks.sliding_window_view(dX,(kw,kh))[::s,::s].reshape(-1,(kw*kh*nc)) # window matrix of dX
    else:
        ac, kc, kw, kh = kernel.shape # kernel width, height and number of channels
        bs, nc, iw, ih = batch_of_images.shape # batch of images' number of images, number of channels, single image's width, single images's height
        #p = 0 # padding
        #s = 1 # stride
        # im2col: Window creation
        window_m = np.lib.stride_tricks.sliding_window_view(batch_of_images,(1,nc,kw,kh))[:,:,::s,::s].reshape(-1,(kw*kh*nc)) # window matrix
        window_m_dx = np.lib.stride_tricks.sliding_window_view(dX,(1,nc,kw,kh))[:,:,::s,::s].reshape(-1,(kw*kh*nc)) # window matrix of dX
    # Convolution
    kernel = kernel.reshape((kw*kh*nc),-1)
    c_m = window_m @ kernel # convolved image matrix
    # ReLU activation
    r_c_m = np.maximum(0,c_m) # convolved image matrix after ReLU activation
    r_c_m[r_c_m>0]=1 # Backward ReLU
    print("dX,X,kernel shapes")
    print(window_m_dx.shape)
    print(window_m.shape)
    print(kernel.shape)


X=np.arange(1,4*4+1).reshape(4,4)
k = np.ones(1*2*2).reshape(2,2)
print("X")
print(X)
print("k")
print(k)
X_c = ReLU_Convolution(X,k)
print("X_c")
print(X_c)
ReLU_Convolution_Backward(X,k,X_c)


X
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
k
[[1. 1.]
 [1. 1.]]
X_c
[[14. 18. 22.]
 [30. 34. 38.]
 [46. 50. 54.]]
This is the backward of the ReLU Convolution
dX,X,kernel shapes
(4, 4)
(9, 4)
(4, 1)


### Max Pooling Layer

In [ ]:
def MaxPooling(boi, winSize=2, stride=2):
    bs, nc, H_in, W_in = boi.shape

    H_out = math.floor((H_in - winSize) / stride) + 1
    W_out = math.floor((W_in - winSize) / stride) + 1

    output_window_shape = (bs, nc, H_out, W_out, winSize, winSize)
    
    y_windows = np.lib.stride_tricks.as_strided(boi, shape=output_window_shape)

    reshaped_y_for_max = y_windows.reshape(bs * nc * H_out * W_out, winSize * winSize)
    
    indices = np.argmax(reshaped_y_for_max, axis=1) # Indici piatti (0 a winSize*winSize-1)
    max_values = reshaped_y_for_max.max(axis=1)
    
    pooled_output = max_values.reshape(bs, nc, H_out, W_out)
    
    cache = (boi.shape, indices, winSize, stride) # indices è 1D
    return pooled_output, cache

def BackwardMaxPooling(d_out, cache):

    A_prev_shape, indices_flat, winSize, stride = cache
    bs, nc, H_prev, W_prev = A_prev_shape
    _, _, H_out, W_out = d_out.shape

    dA_prev = np.zeros(A_prev_shape)

    idx_row_in_window = indices_flat // winSize
    idx_col_in_window = indices_flat % winSize  


    b_idx, ch_idx, r_out_idx, c_out_idx = np.indices((bs, nc, H_out, W_out))

    vert_start = r_out_idx * stride 
    horiz_start = c_out_idx * stride 

    idx_row_in_window_reshaped = idx_row_in_window.reshape(bs, nc, H_out, W_out)
    idx_col_in_window_reshaped = idx_col_in_window.reshape(bs, nc, H_out, W_out)
    
    abs_row_coords = vert_start + idx_row_in_window_reshaped 
    abs_col_coords = horiz_start + idx_col_in_window_reshaped 
    
    indices_for_add_at = (
        b_idx,                  
        ch_idx,                 
        abs_row_coords,         
        abs_col_coords        
    )
    
    np.add.at(dA_prev, indices_for_add_at, d_out)
    
    return dA_prev

#X = np.arange(1,33).reshape(2,1,4,4)
#X[0,0,0,0]=100
#
#pooled,cache = MaxPooling2D(X)
#print(cache)
#dX = np.array([1,5,2,9,4,3,2,8]).reshape(2,1,2,2)
#new_X = backward_maxpool_vectorized(dX,cache)
#print(new_X)


### MLP Layer

In [ ]:
def softmax(x):
    e_x = np.exp(x - np.max(x,axis=-1,keepdims=True))  # for numerical stability
    return e_x / np.sum(e_x,axis=-1,keepdims=True)

def ReLU_SoftMax_FullyConnected(input_array,w1,b1,w2,b2):
    fl = (input_array @ w1)+b1 # first layer
    fa = np.maximum(0,fl) # first activation: ReLU
    sl = (fa @ w2)+b2 # second layer
    sa = softmax(sl) # second activation: SoftMax
    return fl,fa,sl,sa

#print(softmax([1,2,3,100000]))
#print(softmax_no_NS([1,2,3,1000]))
#r = np.array(np.array([1,2,777,2]))
#print(softmax(r))
#r = np.array((np.array([1,2,777,2]),np.array([1,2,777,2]),np.array([1,2,777,2])))
#print(softmax(r))

### Loss function
For this classification problem, the best loss function is the cross-entropy

In [ ]:
def crossEntropy(p,t):
    # p stands for prediction and t stands for true label
    # p = [0,0,1] and t = [1,0,0]
    p = p+(1/100000) # for numerical stability
    return -np.dot(t,np.log(p).T)

#c = [1,1000000000000000,1,1]
#c = softmax(c)
#print(c)
#c = crossEntropy(c,[0,1,0,0])
#print(c)

## Training
To train the model, computing the gradients is necessary. let's start from the cross-entropy

In [ ]:
import time
bs=1 # batch size
#ac is the adaptive channel, the number that corresponds to the amount of channels that the image has
ac, kw, kh, kc = [1,3,3,32]
k1 = np.random.rand(ac*kw*kh*kc).reshape(ac,kw,kh,kc)
kc2 = 64
ac2 = 32
k2 = np.random.rand(ac2*kw*kh*kc2).reshape(ac2,kw,kh,kc2)
h1 = 250
w1 = np.random.rand(1600*250).reshape(1600,250)
b1 = np.random.rand(250).reshape(1,250)
w2 = np.random.rand(250*10).reshape(250,10)
b2 = np.random.rand(10).reshape(1,10)
length = 1 #labels.shape[0]
lr = 0.01
num_epochs = 1
loop= tqdm(range(0,num_epochs,bs))
for epoch in loop:
    avg_loss = []
    start_time = time.time()
    for i in range(0,length,bs):
        rs1 = ReLU_Convolution(images[i:(i+bs)].reshape(bs,1,28,28),k1) 
        loop.set_postfix(average_loss=sum(avg_loss)/(len(avg_loss)+1),state=f"{round(100*i/length,2)}%")
        im_sh1,mpInd1,mp1 = MaxPooling(rs1)
        rs2 = ReLU_Convolution(mp1,k2)
        im_sh2,mpInd2,mp2 = MaxPooling(rs2)
        i_mlp = mp2.flatten()
        fl,fa,sl,pred = ReLU_SoftMax_FullyConnected(i_mlp,w1,b1,w2,b2)

        # Loss
        loss = crossEntropy(pred,labels[i:(i+bs)])
        avg_loss.append(loss)

        # Backward
        dL_dz2 = pred-labels[i:(i+bs)]
        dL_dw2 = fa.T @ dL_dz2
        dL_db2 = np.sum(dL_dz2, axis=0)
        dL_dfa = dL_dz2 @ w2.T
        dReLU = (fl > 0).astype(float)
        dL_dfl = dL_dfa * dReLU
        print(i_mlp.shape)
        dL_dw1 = i_mlp.reshape(bs, -1).T @ dL_dfl
        dL_db1 = np.sum(dL_dfl, axis=0)
        dL_i_mlp = dL_dfl @ w1.T

        


        w1 -= lr*dL_dw1
        b1 -= lr*dL_db1
        w2 -= lr*dL_dw2
        b2 -= lr*dL_db2
    loop.set_postfix(average_loss=sum(avg_loss)/len(avg_loss),state=f"{round(100*i/length,2)}%")
    end_time = time.time()

100%|██████████| 1/1 [00:00<00:00, 76.24it/s, average_loss=[[2.27330587]], state=0.0%]

(1600,)


## Tests

### Inefficient Max Pooling Layer VS Efficient Max Pooling layer for Inference

In [ ]:
#import time
################## PARAMETERS ###########################
#
#bs=1 # batch size
##ac is the adaptive channel, the number that corresponds to the amount of channels that the image has
#ac, kw, kh, kc = [1,3,3,32]
#k1 = np.random.rand(ac*kw*kh*kc).reshape(ac,kw,kh,kc)
#kc2 = 64
#ac2 = 32
#k2 = np.random.rand(ac2*kw*kh*kc2).reshape(ac2,kw,kh,kc2)
#h1 = 250
#w1 = np.random.rand(1600*250).reshape(1600,250)
#b1 = np.random.rand(250).reshape(1,250)
#w2 = np.random.rand(250*10).reshape(250,10)
#b2 = np.random.rand(10).reshape(1,10)
#
################## INFERENCE #############################
#length = 1000 # images.shape[0]
#start_time = time.time()
#for i in tqdm(range(0,length,bs)):
#    continue
#    rs1 = ReLU_Convolution(images[i:(i+bs)].reshape(bs,1,28,28),k1) 
#    # For convolution only, these are the times for processing all the images
#    # 11.0 seconds with bs = 10000
#    # 10.0 seconds with bs = 1000
#    # 09.9 seconds with bs = 100
#    # 08.0 seconds with bs = 10
#    # 06.0 seconds with bs = 1
#    # Why ? the window creation scales as O(N*W) where W is the window size and N is the dimensions of the image.
#    # Since images are stacked, they end up resulting as a single very big image which may cause problems.
#    mp1 = MaxPooling2D(rs1)
#    rs2 = ReLU_Convolution(mp1,k2)
#    mp2 = MaxPooling2D(rs2)
#    i_mlp = mp2.flatten()
#    fl,fa,sl,pred = ReLU_SoftMax_FullyConnected(i_mlp,w1,b1,w2,b2) #softmax doesn't work properly if batch_size > 1
#end_time = time.time()
#print(f"Loop with inefficient MaxPooling took: {round(end_time-start_time,2)}")
#start_time = time.time()
#for i in tqdm(range(0,length,bs)):
#    continue
#    rs1 = ReLU_Convolution(images[i:(i+bs)].reshape(bs,1,28,28),k1) 
#    # For convolution only, these are the times for processing all the images
#    # 11.0 seconds with bs = 10000
#    # 10.0 seconds with bs = 1000
#    # 09.9 seconds with bs = 100
#    # 08.0 seconds with bs = 10
#    # 06.0 seconds with bs = 1
#    # Why ? the window creation scales as O(N*W) where W is the window size and N is the dimensions of the image.
#    # Since images are stacked, they end up resulting as a single very big image which may cause problems.
#    mp1 = MaxPooling2D_Ef(rs1)
#    rs2 = ReLU_Convolution(mp1,k2)
#    mp2 = MaxPooling2D_Ef(rs2)
#    i_mlp = mp2.flatten()
#    fl,fa,sl,pred = ReLU_SoftMax_FullyConnected(i_mlp,w1,b1,w2,b2)
#    #loss = crossEntropy
#end_time = time.time()
#print(f"Loop with efficient MaxPooling took: {round(end_time-start_time,2)} seconds")

100%|██████████| 1000/1000 [00:00<?, ?it/s]


Loop with inefficient MaxPooling took: 0.05


100%|██████████| 1000/1000 [00:00<?, ?it/s]

Loop with efficient MaxPooling took: 0.0 seconds
